//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_BAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class asal_sekolah
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public asal_sekolah()
        {
            this.Siswas = new HashSet<Siswa>();
        }
    
        public int id_asal_sekolah { get; set; }
        public string asal_sekolah1 { get; set; }
        public Nullable<int> npsn { get; set; }
        public string alamat_sekolah { get; set; }
        public string kecamatan { get; set; }
        public string kabupaten_kota { get; set; }
        public string provinsi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siswa> Siswas { get; set; }
    }
}
