//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_BAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ibu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ibu()
        {
            this.Siswas = new HashSet<Siswa>();
        }
    
        public int Id_ibu { get; set; }
        public Nullable<int> nik_ibu { get; set; }
        public string nama_ibu { get; set; }
        public Nullable<System.DateTime> tanggal_lahir_ibu { get; set; }
        public string pekerjaan_ibu { get; set; }
        public string alamat_ibu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siswa> Siswas { get; set; }
    }
}
