//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_BAD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SPSBEntities : DbContext
    {
        public SPSBEntities()
            : base("name=SPSBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<asal_sekolah> asal_sekolah { get; set; }
        public virtual DbSet<ayah> ayahs { get; set; }
        public virtual DbSet<ibu> ibus { get; set; }
        public virtual DbSet<nik> niks { get; set; }
        public virtual DbSet<Siswa> Siswas { get; set; }
        public virtual DbSet<wali> walis { get; set; }
    }
}
