//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_BAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siswa
    {
        public int Id_siswa { get; set; }
        public string nama { get; set; }
        public Nullable<int> nisn { get; set; }
        public Nullable<int> nik { get; set; }
        public Nullable<System.DateTime> tahun_ajaran { get; set; }
        public Nullable<int> asal_sekolah { get; set; }
        public Nullable<int> wali { get; set; }
        public Nullable<int> ayah { get; set; }
        public Nullable<int> ibu { get; set; }
    
        public virtual asal_sekolah asal_sekolah1 { get; set; }
        public virtual ayah ayah1 { get; set; }
        public virtual ibu ibu1 { get; set; }
        public virtual nik nik1 { get; set; }
        public virtual wali wali1 { get; set; }
    }
}
